version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kb
    networks:
      - elastic
    ports:
      - "5601:5601"
    environment:
      - https://elastic:9200

networks:
  elastic:
    driver: bridge
